# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:stable"
  amd64: "ghcr.io/hassio-addons/base/amd64:stable"
  armhf: "ghcr.io/hassio-addons/base/armv7:stable"
  armv7: "ghcr.io/hassio-addons/base/armv7:stable"
  i386: "ghcr.io/hassio-addons/base/i386:stable"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Sell Assistant"
  org.opencontainers.image.description: "AI-powered assistant for selling used items with Google Sheets integration."
  org.opencontainers.image.source: "https://github.com/guiman87/sell-assistant"
  org.opencontainers.image.licenses: "MIT License"
